extraction:
  cpp:
     prepare:
        packages: 
          - libboost-all-dev
          - bison
     index:
        build_command:
        - cp cfe/cmake/Makefile.sample Makefile
        - cp -r cfe/cmake/sample_defs sample_defs
        - make prep
        - make



